name: Java CI

on: 
  push:
    branches:
    - master
    paths-ignore:
    - 'CHANGELOG.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate changelog
      uses: zthulj/changelog-and-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: zthulj
